Repository HTBLA-Grieskirchen/YAMS, pull requests merged in 2022-11, with the labels that each got.

#32 Client modelling
  frontend/src/model/client.ts
Labels: enhancement, web ui

#37 Add Dialog API
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/DialogOverlay.tsx
  frontend/src/components/NotificationComponent.tsx
  frontend/src/components/Notifications.tsx
  frontend/src/libs/dialog.ts
  frontend/src/libs/notification.ts
  frontend/src/pages/_layout.tsx
  frontend/src/pages/index.tsx
  frontend/src/stores/dialogStore.ts
  frontend/src/stores/index.tsx
  frontend/src/stores/notificationStore.ts
  frontend/src/util/types.ts
Labels: enhancement, web ui

#34 Client data form
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ClientRegisterForm.tsx
  frontend/src/model/address.ts
  frontend/src/pages/client/add/index.tsx
Labels: enhancement, web ui, database

#43 Features from Address Branch
  backend/setup.sql
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ClientRegisterForm.tsx
  frontend/src/components/CountryItem.tsx
  frontend/src/components/HomeTile.tsx
  frontend/src/components/SubmenuLayout.tsx
  frontend/src/components/country/CountryAddItem.tsx
  frontend/src/components/country/CountryDetailItem.tsx
  frontend/src/components/country/CountryEditItem.tsx
  frontend/src/components/country/CountryListEntry.tsx
  frontend/src/components/country/CountryTableHeader.tsx
  frontend/src/components/country/CountryUsageTabs.tsx
  frontend/src/config/frontendConfig.ts
  frontend/src/config/index.ts
  frontend/src/libs/database/country.ts
  frontend/src/libs/database/index.ts
  frontend/src/model/address.ts
  frontend/src/model/city.ts
  frontend/src/model/country.ts
  frontend/src/model/surreal/index.ts
  frontend/src/pages/addresses/_layout.tsx
  frontend/src/pages/addresses/city/index.tsx
  frontend/src/pages/addresses/country/index.tsx
  frontend/src/pages/index.tsx
  frontend/src/stores/addressStore.ts
  frontend/src/stores/configStore.ts
  frontend/src/stores/index.tsx
  frontend/src/util/helpers.ts
  frontend/src/util/paths.ts
Labels: documentation, enhancement, web ui, database
